// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBF7P7ST_BCUKhntwutlbgcobWy5wAwYs',
    appId: '1:999810256891:web:742323ed5a3fe37a91055e',
    messagingSenderId: '999810256891',
    projectId: 'edutrack-f2192',
    authDomain: 'edutrack-f2192.firebaseapp.com',
    storageBucket: 'edutrack-f2192.firebasestorage.app',
    measurementId: 'G-F0PX0JQ8M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAln0OfNtxuuXoHtJfeflTYqAZu_ytTeSo',
    appId: '1:999810256891:android:8fc8914fd6f3f80a91055e',
    messagingSenderId: '999810256891',
    projectId: 'edutrack-f2192',
    storageBucket: 'edutrack-f2192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHuU9NSTFZCQYg0_tTmNZf8yYjpSq6d-k',
    appId: '1:999810256891:ios:6f2a85473259565a91055e',
    messagingSenderId: '999810256891',
    projectId: 'edutrack-f2192',
    storageBucket: 'edutrack-f2192.firebasestorage.app',
    iosBundleId: 'com.example.edutrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHuU9NSTFZCQYg0_tTmNZf8yYjpSq6d-k',
    appId: '1:999810256891:ios:6f2a85473259565a91055e',
    messagingSenderId: '999810256891',
    projectId: 'edutrack-f2192',
    storageBucket: 'edutrack-f2192.firebasestorage.app',
    iosBundleId: 'com.example.edutrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBF7P7ST_BCUKhntwutlbgcobWy5wAwYs',
    appId: '1:999810256891:web:2f61f166e8bade5091055e',
    messagingSenderId: '999810256891',
    projectId: 'edutrack-f2192',
    authDomain: 'edutrack-f2192.firebaseapp.com',
    storageBucket: 'edutrack-f2192.firebasestorage.app',
    measurementId: 'G-97GVX97Y3B',
  );
}
